pycram/src/pycram/bullet_world.py, pycram/src/pycram/bullet_world_reasoning.py
This PR changes  the way the Visible and Occluding reasoning queries work, in order to fix the problems with the frequently tf publisher from #16.
The new implementation works by creating new BulletWorlds, which are a copy of the original one, and doing the reasoning in this world. 
By doing this the objects don't have to be moved in the original BulletWorld and thus no inconsistent tf should occur. 
Furthermore, a remove function was added to the Object class which detaches the object from all attachments and then removes it from the BulletWorld
=> New detecting

src/pycram/knowrob.py
Added a file for knowrob queries which use the rosprolog python interface.
=> Knowrob interface clea

src/pycram/__init__.py, src/pycram/bullet_world.py, src/pycram/bullet_world_reasoning.py, src/pycram/costmaps.py, src/pycram/location_designator.py, src/pycram/pose_generator_and_validator.py, src/pycram/resolver/location_designator_grounding.py
This PR extends #33  by using the implemented costmaps as basis for resolving location designator. This realized via a new resolver for location designator as well as generator and validator for poses sampled from the costmap. 
At the moment the location designator supports the constrains ```reachable_for``` and ```visible_for``` and a target for these constrains. 
```
LocationDesignator(CostmapLocationDesignatorDescription(reachable_for=robot, visible_for=robot, target=milk))
```
This location designator describes a location from which the target, in this case the milk, is visible and reachable for the robot. 
The target can either be a position in world coordinate frame or an object in the BulletWorld. 
This PR includes and depends on #33 , therefore this should be merged beforehand.
=> Location generator

demos/pycram_bullet_world_demo/demo.py, src/pycram/__init__.py, src/pycram/process_modules/available_process_modules.py, src/pycram/process_modules/boxy_process_modules.py, src/pycram/process_modules/donbot_process_modules.py, src/pycram/process_modules/hsr_process_modules.py, src/pycram/process_modules/pr2_process_modules.py, src/pycram/robot_description.py
[[process_modules] restructured process_modules and cleaned up a bit](https://github.com/cram2/pycram/pull/44/commits/79b5edf90376086297157a6faa08fc890be14ea7)
=> [process_modules] restructured process_modules and cleaned up a bit

demos/pycram_bullet_world_demo/demo.py, demos/pycram_tasktree_demo/README, demos/pycram_tasktree_demo/scripts/demo_bullet.py, demos/pycram_tasktree_demo/scripts/pr2_knowledge.py, src/pycram/__init__.py, src/pycram/designator.py, src/pycram/designators/action_designator.py, src/pycram/designators/location_designator.py, src/pycram/designators/motion_designator.py, src/pycram/designators/object_designator.py, src/pycram/resolver/desig_resolution.py, src/pycram/resolver/location_designator_grounding.py, src/pycram/resolver/motion_designator_grounding.py, src/pycram/resolver/object_designator_grounding.py, src/pycram/resolver/plans.py, src/pycram/test/test_location_designator_grounding.py, src/pycram/test/test_object_designator_grounding.py
The question here is; is there any fabulous import? idk, my idea would be to make everything from the designators available at all times since this is the main structure the demos are working with. No need to import them one by one? For now, I did it like this but this def breaks the task_tree demo I'm just checking the other demo all the time to see if it still runs. But within the task_tree there are still motion_designators and stuff, what do u think @Tigul?
=> [designators] restructured designators

src/pycram/bullet_world.py
This PR adds a function to the Object class which allows to change the color of any link. 
The function takes a color as RGBA values and optional a link name which should be colored.
There is also a method for getting the color of an object or the link of an object. This method has the optional argument of a link name, if there is no link name specified the method returns a dictionary with every colored link and its color.
=> [bullet-world] added a function to change colors of links

src/pycram/bullet_world.py, src/pycram/bullet_world_reasoning.py, src/pycram/costmaps.py, src/pycram/pose_generator_and_validator.py
Now blocking and reachable in bullet_world_reasoning also use the new IK solver with correct positions for the wrist and correct kinematic chains. They also use the shadow world now.
Furthermore, a few methods now raise an Error instead of returning None. This should improve usablility since the source of an error should be more obvious.
=> Fast fixes

src/pycram/costmaps.py, test/test_bullet_world.py, test/test_costmaps.py
Hopefully fixed the bug in rayTestBatch. Solution now is to redo the rayTestBatch call if it returns None.  
In a quantitive Test of around 1000 attempts this seems to work, however there is now also a Test which creates 300 Occupancy costmaps to try and recreate this bug.
=> Raytest bug

doc/requirements.txt, doc/source/conf.py, doc/source/index.rst, doc/source/notebooks/minimal_task_tree.ipynb, doc/source/remarks.rst, doc/source/task_trees.rst, examples/minimal_task_tree.ipynb, src/pycram/task.py, test/test_bullet_world.py, test/test_location_designator_grounding.py, test/test_task_tree.py
Added to_json methods for task trees and tutorials on the usage of task trees.
=> JSON Serialization of Task Trees and Tutorials for Task Trees.

doc/source/index.rst, doc/source/notebooks/orm_example.ipynb, doc/source/orm.rst, examples/orm_example.ipynb, requirements.txt, src/pycram/designators/action_designator.py, src/pycram/orm/action_designator.py, src/pycram/orm/base.py, src/pycram/orm/task.py, src/pycram/task.py, test/test_bullet_world.py, test/test_orm.py, test/test_task_tree.py
ORM package for pycram including tests, examples and documentation.
=> ORM package for pycram.

examples/minimal_task_tree.ipynb, src/pycram/costmaps.py, src/pycram/task.py
Some smaller fixes to make the presentation more smoothly
=> Smaller fixes

src/pycram/pose_generator_and_validator.py
=> [pose-valid] added contact checking to reachability valdator

src/pycram/costmaps.py, test/test_costmaps.py
Excludes objects attached to the robot when creating an OccupancyCostmap
=> Occupany exculsion

doc/source/examples.rst, examples/orm_example.ipynb, src/pycram/designators/action_designator.py, src/pycram/designators/object_designator.py, src/pycram/enums.py, src/pycram/orm/action_designator.py, src/pycram/orm/base.py, src/pycram/orm/task.py, src/pycram/task.py, test/test_orm.py
Added a MetaData table for logging and filled it automatically. Wrote tests and updated doc for it.
=> MetaData for Logging

src/pycram/pose.py
Solves the problem with the shaky cam
=> [pose] optimized rotational normalization

examples/local_transformer.ipynb
this is for the  local_transformer of pycram
=> []examples] added a very small jypter nbook

demos/pycram_bullet_world_demo/run.py, doc/source/installation.rst, src/pycram/bullet_world.py, src/pycram/helper.py, src/pycram/local_transformer.py, src/pycram/pose.py, src/pycram/process_modules/pr2_process_modules.py
This PR adds a lot of optimization to PyCRAM, especially with the handling of Transforms for the local transformer. Overall this leads to a speed up of ca. 5 times. Benchmarking is done on the pycram_bullet_world_demo and unittests. 
Profile of the demo without optimization: 
Profile of the demo with optimization: 
Without optimization: 3 min 5 sec
With optimization: 23 sec 316 ms
=> Transforn optimization

examples/custom_resolver.ipynb, src/pycram/resolver/location/jpt_location.py
=> Fixed jpt example

src/pycram/designator.py, src/pycram/designators/action_designator.py, src/pycram/helper.py
the special knowledge needs a better place and the pr_1 link is a bit annoying maybe we could find a better way for that.
=> [action-desig-pickup]added everything for the pickup similar to cram

src/pycram/external_interfaces/giskard.py, src/pycram/external_interfaces/robokudo.py
Fixes the import issue when Robokudo messaged could not be imported. Also fixes the problem that giskard needs to run before pycram is launched.
=> Fix interface imports

doc/source/examples.rst, doc/source/notebooks/robokudo.ipynb, examples/interface_examples/giskard.ipynb, examples/interface_examples/robokudo.ipynb, launch/ik_and_description.launch, resources/hsrb.urdf, src/pycram/__init__.py, src/pycram/external_interfaces/giskard.py, src/pycram/external_interfaces/robokudo.py, src/pycram/process_modules/hsr_process_modules.py, src/pycram/robot_descriptions/hsr_description.py
Adds an example for the robokudo interface. Furthermore, there is a complete overhaul in how the robokudo and giskard interfaces are initialized. Lastly, there are some minor changes to increase the compatibility of the HSR between PyCRAM and Giskard.
=> Robokudo example

README.md, doc/source/conf.py, doc/source/index.rst, doc/source/troubleshooting.rst
This PR adds a little troubleshooting page with the most common errors. This will be extended in the future.
=> [doc] Added a troubleshooting section

doc/source/_ext/console_lexer.py, doc/source/_pygments/style.py, doc/source/conf.py, doc/source/installation.rst, doc/source/remarks.rst, doc/source/troubleshooting.rst
Added a new custom style which resembles the sphinx style but has better highlighting. Also adds a new Lexer which extends the BashLexer by new keywords for better readability in the shell code-blocks.
=> Pygments addons

examples/action_designator.ipynb, examples/bullet_world.ipynb, examples/cram_plan_tutorial.ipynb, examples/interface_examples/giskard.ipynb, examples/interface_examples/robokudo.ipynb, examples/intro.ipynb, examples/location_designator.ipynb, examples/motion_designator.ipynb, examples/object_designator.ipynb, examples/pose.ipynb
Re-formulated some explanations within the examples and fixed typos. Hope it helps!
=> Fixing typos in examples

doc/source/installation.rst
Just documentation on virtualenv
=> Add explanation to virtualenv and pycharm setup

src/pycram/datastructures/enums.py
Added types for the following objects: Metalmug, Pringles, Human
=> [enums]: added additional ObjectTypes

.devcontainer/README.md, .devcontainer/devcontainer.json, .devcontainer/script.sh
The file can be run locally or on GitHub codespaces.
=> Added Devcontainer config file

src/pycram/external_interfaces/move_base.py
hsrb for example, is moved in real with move_base
=> [move_base] added move_base interface to external interface

src/pycram/designator.py
Change loginfo to old style string formatting.
=> Fix bug in ObjectDesignatorDescription class

src/pycram/__init__.py, src/pycram/datastructures/pose.py, src/pycram/datastructures/world.py, src/pycram/local_transformer.py, src/pycram/world_reasoning.py
Some small optimization for Pose and Transformations. 
* The quaternion normalization of Pose was changed to list comprehention
* When transforming a Pose only the affected objects will update their transforms.
=> Optimization 24

src/pycram/designators/object_designator.py, src/pycram/external_interfaces/giskard.py, src/pycram/external_interfaces/robokudo.py, src/pycram/process_modules/pr2_process_modules.py, src/pycram/process_modules/stretch_process_modules.py
updated robokudo interface with new queries
=> [robokudo interface] new queries for the newest robokudo mainly suturo

requirements.txt, src/pycram/costmaps.py, src/pycram/worlds/bullet_world.py
This PR changes the pybullet dependency to the new pycram_bullet which allows for more than 128 links in an URDF
=> Pycram bullet

examples/interface_examples/giskard.md, examples/intro.md, examples/language.md, examples/location_designator.md, examples/migrate_neems.md, examples/motion_designator.md, examples/orm_example.md
Code and docs have diverged...
Fixes #200
=> Fix issues in documentation

binder/README.md, binder/pycram-http.rosinstall, doc/source/installation.rst, doc/source/remarks.rst, doc/source/troubleshooting.rst, package.xml, pycram-https.rosinstall, pycram.rosinstall, requirements.txt
See individual commit messages for details
=> Improve installation process

test/test_multiverse.py
It fixes the spawning of milk_box in test_multiverse.py to use the XML version, not the urdf.
=> Fixes Multiverse test issue

src/pycram/external_interfaces/giskard.py, src/pycram/process_modules/__init__.py, src/pycram/process_modules/tiago_process_modules.py
Added PMs for the real Tiago, except the ones for the gripper. Also fixed some wrong lines in the giskard interface
=> [process modules] Added process modules for the real Tiago

src/pycram/local_transformer.py
Fixed bug where the local transformer gets the names of the involved objects from the frame name and then searches for the objects with these names without checking in which world these objects exist.
=> [LocalTransformerBugFix] corrected used world in update transforms.

src/pycram/datastructures/enums.py, src/pycram/ros/logging.py, test/test_logging.py
I added the ability to set the log level for pycram logging.
=> [LoggingLevel] Adding setting log level.

src/pycram/ros/ros_tools.py, src/pycram/ros_utils/joint_state_updater.py, src/pycram/ros_utils/object_state_updater.py
For real robot also the environment as state updater so we update the believe state with giskard
=> [environment_joint_state] added joint state updater for environment

.github/workflows/new-pycram-ci.yml, demos/pycram_bullet_world_demo/demo.py, demos/pycram_bullet_world_demo/test_demo.py, src/pycram/designators/action_designator.py, src/pycram/knowledge/knowledge_sources/facts_knowledge.py
This PR adds the bullet world demo to the CI to ensure it will be tested
=> [ci] Added demo to test ci 

src/pycram/ros_utils/object_state_updater.py
added clear buffer and a wait for transform to make it more robust when working on real robot, otherwise the tf trees can be seperated
=> [robotStateUpdater] making this more robust

src/pycram/process_modules/pr2_process_modules.py, src/pycram/ros_utils/viz_marker_publisher.py
adjustments for real robot eg. move_base for nav instead of giskard Gripper open and close with enums and bug in calculation for head
=> Pr2 process module

binder/Dockerfile, binder/pycram-http.rosinstall, src/pycram/designators/action_designator.py
=> [vrb] added other designators

README.md, demos/pycram_bullet_world_demo/demo.py, doc/source/index.rst, examples/action_designator.md, examples/cram_plan_tutorial.md, examples/improving_actions.md, examples/intro.md, examples/language.md, examples/migrate_neems.md, examples/minimal_task_tree.md, examples/orm_example.md, src/pycram/datastructures/enums.py, src/pycram/designators/action_designator.py, src/pycram/orm/action_designator.py, src/pycram/robot_description.py, src/pycram/robot_descriptions/armar_description.py, src/pycram/robot_descriptions/boxy_description.py, src/pycram/robot_descriptions/donbot_description.py, src/pycram/robot_descriptions/hsrb_description.py, src/pycram/robot_descriptions/icub3_description.py, src/pycram/robot_descriptions/justin_description.py, src/pycram/robot_descriptions/pr2_description.py, src/pycram/robot_descriptions/stretch_description.py, src/pycram/robot_descriptions/tiago_description.py, test/test_designator/test_action_designator.py, test/test_designator/test_move_and_pick_up.py, test/test_designator/test_move_and_place.py, test/test_language.py, test/test_orm/test_orm.py, test/test_task_tree.py
[TorsoState] MoveTorso now accepts newly added abstract 'TorsoState' instead of specific values, which allows us to define static joint states for more complex torsos
=> [TorsoState] Introduction of abstract torso states to better represent complex torsos

resources/objects/apartment.urdf, resources/objects/apartment_without_walls.urdf
Change the door joints limits and from prismatic to revolute, similar to https://github.com/code-iai/iai_maps/pull/118
@hawkina since I asked you to look into the iai_maps PR already, could you verify this one too please?
=> Fix joint for fridge door

requirements.txt, src/pycram/helper.py
The two functions are essentially designed to make the action more semantic, as requested and discussed.
=> Semantic representation

src/pycram/cache_manager.py, src/pycram/datastructures/world.py, src/pycram/description.py, src/pycram/designators/action_designator.py, src/pycram/object_descriptors/generic.py, src/pycram/object_descriptors/urdf.py, src/pycram/world_concepts/world_object.py, test/test_butterworth_filter.py
=> [objects/test] Removed deprection warning and improved filter test

src/pycram/datastructures/enums.py, src/pycram/datastructures/pose.py, src/pycram/designators/action_designator.py, src/pycram/designators/motion_designator.py, src/pycram/tasktree.py
Added ```__str__()``` and ```__repr__()``` methods to all performables
Added a method ```render(filename: str)``` to the ```TaskTree```
=> Render task tree

config/world_conf.py, examples/improving_actions.md, scripts/generate_database_for_ci.py, src/pycram/datastructures/enums.py, src/pycram/datastructures/pose.py, src/pycram/datastructures/world.py, src/pycram/designators/action_designator.py, src/pycram/designators/motion_designator.py, src/pycram/process_module.py, src/pycram/tasktree.py, src/pycram/testing.py, test/test_failure_handling.py
depends on #280 (because I forgot to make a separate branch :sweat_smile: )
Make execution delay a timedelta instead of boolean.
=> Execution delay

examples/improving_actions.md, scripts/generate_database_for_ci.py, src/pycram/datastructures/enums.py, src/pycram/datastructures/pose.py, src/pycram/designators/action_designator.py, src/pycram/designators/motion_designator.py, src/pycram/process_module.py, src/pycram/tasktree.py, src/pycram/testing.py, test/test_failure_handling.py
depends on #281 
Added the possibility to hook callbacks to task tree for specific action types.
=> Tasktree callback

src/pycram/external_interfaces/pinocchio_ik.py, test/test_external_interfaces/test_pinocchio.py
Adds some simple tests for the pinocchio ik solver implementation as well as some code comments to make the ik solver code more understandable
=> [tests] Added tests for pinocchio ik solver

src/pycram/external_interfaces/blum_api.py
Introduces a first version of the Blum API to control the apartment kitchen
=> First version of the blum api

src/pycram/datastructures/world.py, src/pycram/designators/action_designator.py, src/pycram/process_modules/default_process_modules.py, src/pycram/world_concepts/world_object.py, src/pycrap/ontologies/crax/classes.py, test/test_designator/test_action_designator.py, test/test_orm/test_ormatic_designator.py
wip i will rework this but for now its a quick fix
=> [Perception] fixed detect and small changes on pouring

src/pycram/designators/action_designator.py
will be changed within the next week
=> [mixing-action] wip v1 

README.md
Updated wording of README to improve clarity
=> Improve README.md wording

src/pycram/failures.py
First string was missing the format specified **f**'...'
=> Fix format string

src/pycram/designators/action_designator.py
Based on TransportAction but without the NavigationAction
=> Add PickAndPlaceAction
