cram2/pycram

- pycram/src/pycram/bullet_world.py
- pycram/src/pycram/bullet_world_reasoning.py
* Complete support for multiple BulletWorld
* A function to copy an existing BulletWorld
The support for more than one BulletWorld is largely done by adding the `physicClientID` argument to all statements which call PyBullet directly. Furthermore a function was added which creates a new BulletWorld and copies the state of the existing BulletWorld to the newly created one. This BulletWorld, however is in "direct mode" which means there is no graphical representation of the simulation. 
Because this PR is based on the work of the Pull Requests #2  #3 and #4 these PRs should be merged before this one.
> Multiverse

- src/pycram/bullet_world.py
- src/pycram/robot_description.py
- src/ros/joint_state_publisher.py
- src/ros/ros_topic_publisher.py
- src/ros/rosbridge.py
- src/ros/tf_broadcaster.py
In the current implementation of ROSBridge as a singleton metaclass, it was easy to trigger a deadlock: When a class inheriting from SingletonMeta tried to construct a different SingletonMeta in its constructor, the second SingletonMeta instance could never be constructed, because the check for the class happened only AFTER trying to acquire the lock, instead of before.
As an example, consider the following:
```
class A(SingletonMeta):
pass
class B(SingletonMeta):
def __init__(self):
self.a = A()
b = B()     # Deadlock
```
For ROSBridge, a singleton object wasn't even necessary, so I just removed it and simply made it a module with a ros_client global. ros_client is then guaranteed to be instantiated exactly once by the Python import system.
> ROSBridge singleton fix

- launch/ik_and_description.launch
- src/pycram/helper.py
- src/pycram/knowrob/reasoning.py
- src/pycram/location_designator.py
- src/pycram/resolver/location_designator_grounding.py
- src/pycram/resolver/object_designator_grounding.py
- src/pycram/test/test_location_designator_grounding.py
Includes a unit test and a KnowRob-based resolver.
Launch `ik_and_description.launch` before running the unit test in `src/pycram/test/test_location_designator_grounding.py` because it requires KnowRob. 
To use the KnowRob-based designator resolution, you need https://github.com/code-iai/neem-interface/pull/1 in neem-interface.
> Implementation of location designators

- src/pycram/bullet_world.py
- src/pycram/robot_description.py
This PR adds quality of life for loading objects to the BulletWorlld. 
These qos changes are:
Code is added that deletes the created URDF in the PyCRAM cache if loading of the URDF fails. Either if the URDF is malformed or the lookup of ROS packaged failes. This is done to avoid that a faulty file remains in cache while the user fixed the actual file in the resources directory. Additionally the file caching of PyBullet is disabled since this caching would also cache faulty files which can not be removed by a user, resulting in the same problem this PR is trying to solve. 
Also PyCRAM now raises an error if loading of a file fails directly at the point in code where the loading happens and not further down when the program tries to get link and joint information. 
Furthermore there is now …
> Clear urdf from cache when load fails

- src/pycram/bullet_world.py
This PR changes the caching of corrected URDF files. Until now, when creating URDF cache file for a .stl or .obj file the name given to the object was used instead of the filename of the .stl or .obj file 
This PR changes this such that the filename of the mesh file is used for the newly created URDF file. This should prevent problems that sometimes occured when loading mesh files. 
Another addition is the default setting of the gravity which is set to the same value as on earth. Furthermore, a ground plane is now spawned when the bullet world is created
> Load object fix

- src/pycram/costmaps.py
This PR should finally solve the rayTest bug. The problem seemed to be that the shadow world was introduced in a previous PR. The presence of two simulations at a time was what caused this error, to solve the bug rayTesting was moved to the shadow world. 
The implementation was tested on 10000 runs of creating the Occupancy costmap. However, to be sure this is fixed in the long run the test case which creates 300 Occupancy Costmaps is kept.
> [costmaps] moved rayTesting to the shadow world

- src/pycram/bullet_world.py
Some fixes for the remove method of Objects. These fixes are:
* Set the BulletWorld.robot to None if the removed Object was the robot 
* Wait for the shadow object to be removed before removing  the normal object to avoid crashes of the world sync thread
> [bullet-world] fixes in remove method to avoid crashes

- doc/requirements.txt
Error happened because of version incompatability of sphinx
> Fixes for the doc build error

- src/pycram/ros/tf_broadcaster.py
Published TF messages now have the correct time stamp, eliminating the TF_REPEATED_DATA error that was occuring.
> [ros/tf-broadcast] Fixed time in published TF frames

- src/pycram/process_module.py
- src/pycram/process_modules/__init__.py
- src/pycram/process_modules/default_process_modules.py
- src/pycram/robot_descriptions/tiago_description.py
Adds default process modules which only work with the robot description.
> [process-modules] Added default process modules

- src/pycram/designators/action_designator.py
- src/pycram/pose_generator_and_validator.py
Fixes a bug where the retract_pose was calculated within the wrong frame (world). Further more unifies the retract offset to 0.07 (7cm)
Additionally resets the joint state of the robot after each pose generation
> Bugfix retract pose

- binder/Dockerfile
- binder/requirements.txt
Added a specific requirements file for binder as the current numpy version (1.24.3) is incompatible.
> [binder]: added specific requirements for launch

- binder/Dockerfile
Numpy is no longer being uninstalled during binder launch as this was to prevent two numpy installations with different versions.
Since this is resolved, the uninstall needs to be removed to ensure numpy is still installed in the environment.
> [binder]: removed uninstallation of numpy

- src/pycram/world.py
- src/pycram/world_concepts/constraints.py
- src/pycram/world_concepts/world_object.py
- test/test_attachment.py
- test/test_bullet_world.py
Moving prospection world attachments should not move the real world ones, this should fix this issue.
> Fix Attachment In Prospection

- resources/pr2.urdf
The original values caused the PR2 to not work in a pycram simulation.
The new values are generated values with xacro from the original pr2 description
> [pr2_urdf] adjusted values for torso_lift_joint

- src/pycram/description.py
On deletion of constraints, there needed to be a check that the constraint id exists first.
> Fix for Attachment constraint deletion issue

- src/pycram/object_descriptors/generic.py
- src/pycram/world_concepts/world_object.py
- src/pycram/worlds/bullet_world.py
- test/test_object.py
work from bass, tom and me to be able to describe and spawn generic objects for example the robokudo objects
@Author @AbdelrhmanBassiouny 
@Author @tomsch420
> [generic object]  for  perceiving in real world and spawn/describe obbjects from type unkown

- src/pycram/failure_handling.py
- src/pycram/language.py
- test/test_language.py
Introduces the RetryMonitor class, a subclass of FailureHandling, which implements a retry mechanism specifically designed to work with a Monitor. This class aims to improve the robustness of task execution by allowing retries in case the monitoring condition is triggered.
> [failure handling]  A subclass of FailureHandling

- src/pycram/ontology/ontology.py
- src/pycram/ontology/ontology_common.py
- test/test_ontology.py
Related to #141 #166 #191, this PR switches the default SQL-backend to `in-memory` & add general catch of `sqlite3.Error` from owlready2 accessing to SQL backend as a disk-file, to avoid disrupting Designator functionality. 
Specifically,
* `OntologyManager.create_ontology_world()` -> `owlready2.World.set_backend()`, where sqlite3 DB access commands are invoked. Errors may happen upon a corrupt db or concurrent accesses, or a typical `OperationalError` would be raised amid debug process, which if sometimes prematurely ended (eg by pause/stop-debug in IDE), could result in a locked-db file on disk.
Such errors would be treated in another PR, or even better by `owlready2` itself.
https://stackoverflow.com/a/2741015/4767815
Also, A quick resolution is deleting the SQL file on disk.
SQL …
> [OntologyManager] Use in-memory SQL backend by default

- demos/pycram_bullet_world_demo/demo.py
- requirements-resolver.txt
- requirements.txt
- src/pycram/costmaps.py
- src/pycram/datastructures/enums.py
- src/pycram/designators/specialized_designators/probabilistic/probabilistic_action.py
- src/pycram/pose_generator_and_validator.py
- test/test_costmaps.py
- test/test_database_resolver.py
This PR adds the 2D product algebra as a means to express locations for pycram.
> First draft for making semantic costmaps more flexible.

- src/pycram/datastructures/dataclasses.py
- src/pycram/datastructures/world.py
- src/pycram/helper.py
- test/test_attachment.py
Fix for the World Sync bug in the CI.
> World sync ci bug fix

- src/pycram/datastructures/dataclasses.py
- src/pycram/datastructures/world.py
- test/test_multiverse.py
Save joint states when only using the simulator state as the simulator does not save joint states.
Allow the user to specify the state_id when saving as an option for flexibility.
Added a test for save and restore state in multiverse tests.
> Save world state

- src/pycram/failures.py
- src/pycram/language.py
- src/pycram/ros_utils/force_torque_sensor.py
Test out as follows:
```Python
with simulated_robot:
fts = ForceTorqueSensor("pr2")
rospy.sleep(3)  # Give a short time to make sure arrives
plan = Code(lambda: rospy.sleep(1)) * 999999 >> Monitor(fts.human_touch_monitoring)
plan.perform()
print("Detected")
```
> [ForceTorqueMonitoring] Adds Force Torque Monitoring for the real robot

- config/multiverse_conf.py
- config/world_conf.py
- doc/source/orm.md
- examples/cram_plan_tutorial.md
- scripts/test_notebook_examples.sh
- src/pycram/datastructures/enums.py
- src/pycram/designators/action_designator.py
- src/pycram/designators/motion_designator.py
- src/pycram/designators/specialized_designators/probabilistic/probabilistic_action.py
- src/pycram/external_interfaces/giskard.py
- src/pycram/external_interfaces/robokudo.py
- src/pycram/orm/action_designator.py
- src/pycram/orm/motion_designator.py
- src/pycram/process_modules/pr2_process_modules.py
- src/pycram/world_concepts/world_object.py
- test/test_designator/test_action_designator.py
- test/test_designator/test_move_and_place.py
- test/test_knowledge.py
- test/test_orm/test_orm.py
- test/test_task_tree.py
Updates to Giskard interface like:
Allow / Disable gripper collision fix where incorrect links were used + added a configuration parameter and a passable argument to achieve_cartesian_goal.
Use of seed configuration only in projection mode.
Added MovementType Enum to use the correct motion in Giskard.
Added a world configuration parameter that controls the use of  Giskard monitors.
Added a parameter that controls the pickup prepose distance (I think the best solution is to use the knowledge here).
> Giskard fallschool changes

- src/pycram/ros_utils/tf_broadcaster.py
`Time` is defined as a function in `ros/data_types.py`, and thus needs to be called to be usable. Introduced in #205
> Fix call to data_type.Time

- demos/pycram_bullet_world_demo/demo.py
- examples/motion_designator.md
- src/pycram/datastructures/enums.py
- src/pycram/datastructures/world.py
- src/pycram/designators/action_designator.py
- src/pycram/designators/motion_designator.py
- src/pycram/external_interfaces/robokudo.py
- src/pycram/orm/action_designator.py
- src/pycram/orm/motion_designator.py
- src/pycram/process_modules/default_process_modules.py
- src/pycram/process_modules/donbot_process_modules.py
- src/pycram/process_modules/hsrb_process_modules.py
- src/pycram/process_modules/pr2_process_modules.py
- src/pycram/process_modules/stretch_process_modules.py
- src/pycram/process_modules/tiago_process_modules.py
- src/pycram/ros/ros_tools.py
- src/pycram/utils.py
- src/pycrap/objects.py
- test/test_designator/test_action_designator.py
- test/test_orm/test_orm.py
The `DetectAction` now returns a list of all detected objects. It supports various detection techniques:
- **ALL**: `0`
- **HUMAN**: `1`
- **TYPES**: `2`
- **REGION**: `3`
- **HUMAN_ATTRIBUTES**: `4`
- **HUMAN_WAVING**: `5`
Objects perceived in the real world are dynamically spawned into the environment.
- The `get_scene_objects` method serves as a mockup for the `ALL` detection type.
- Detection types like `HUMAN` and `HUMAN_ATTRIBUTES` are **not supported** in the simulation.
In the real Robokudo system, filtering for specific objects is **not supported** by default. While the detection pipeline is correct, if you are using it in a real environment, you must manually filter the objects in your demo.
- The `state` parameter manages continuous perception.
- Default state: `start`.
- The …
> [detectaction] Robokudo real robot

- resources/objects/plane_colored.urdf
- src/pycram/ros_utils/viz_marker_publisher.py
Spawning this floor can be toggled by adjusting the boolean parameter "spawn_floor" in the VizMarkerPublisher
> Added fitting floor for apartment

- src/pycram/knowledge/knowledge_sources/facts_knowledge.py
- src/pycram/robot_descriptions/boxy_description.py
- src/pycram/robot_descriptions/donbot_description.py
- src/pycram/robot_descriptions/hsrb_description.py
- src/pycram/robot_descriptions/pr2_description.py
- src/pycram/robot_descriptions/stretch_description.py
- src/pycram/robot_descriptions/tiago_description.py
- src/pycram/robot_descriptions/ur5_description.py
- src/pycram/robot_descriptions/ur5e_controlled_description.py
Modified descriptions of Tiago, Boxy, UR5, HSR,
Donbot, Stretch.
> Add gripper types to various robot descriptions

- src/pycram/ros_utils/viz_marker_publisher.py
When using the VizMarkerPublisher, the default reference frame is set to `map`.
This is unsuitable when only working in a simulation, as then it usually is `SIMULATED/map`.
Therefore add an option to specify a different reference frame when initiating the publisher.
> Allow to set different reference frame in VizMarkerPublisher

- src/pycram/knowledge/knowledge_sources/facts_knowledge.py
Removed unnecessary setting of object pose to zero to get axis aligned bounding box ... instead just set shift_to_object_pose=False in the get_axis_aligned_bounding_box method.
> [FactsKnowledge] no need to set pose of prospection object to zero.

- src/pycram/datastructures/pose.py
- src/pycrap/ontologies/crax/classes.py
- test/test_pose.py
This adds three new methods to PoseStamped that help with reasoning about orientation between poses in 2D space. The goal is to figure out whether one pose is "facing" another along its local X or Y axis and, based on that, compute a suggested rotation. Particular i need them for my cutting action
New methods:
**is_facing_2d_axis(pose_b, axis='x'):**
Checks if this pose is roughly facing pose_b along the specified axis (X or Y), within a default 82° threshold.
**is_facing_x_or_y(pose_b):**
Returns True if the pose is facing the target pose along either X or Y.
> New functions for Pose Stamped and tests

- src/pycram/cache_manager.py
- test/test_cache_manager.py
- Updated CacheManager to handle both absolute and relative file paths for caching.
- Enhanced error handling to raise FileNotFoundError for non-existent absolute and relative paths.
- Added unit tests to verify the correct behavior of caching with both path types.
> Implement loading of URDFs from absolute and relative paths

- docker/ros2/Dockerfile
Added [iai_robots](https://github.com/code-iai/iai_robots.git) (branch: ros-jazzy) to ros2 dockerfile for CI/CD pipeline.
This is a preparation to multi-robot changes, as more robot models than the pr2 are required for sufficient testing
> Added iai_robots to ros2 dockerfile
